### ISSUE TITLE
Issue with HA 2024.7

### ISSUE THREAD

**Issue by townsmcp** [fano0001/home-assistant-mazda#1]
Adding this here, hopefully @fano0001 you might have more success than @sethcalkins had with https://github.com/runDMCA/home-assistant-mazda/compare/main...SethCalkins:home-assistant-mazda:main

Some suggestions have been added https://github.com/runDMCA/home-assistant-mazda/issues/5#issuecomment-2223110734 that might help point to a fix to the issue

**Comment by SethCalkins** [comment]
https://github.com/runDMCA/home-assistant-mazda/issues/5#issuecomment-2233998275

**Comment by fano0001** [comment]
After updating to HA 2024.8 the integration is working
